### ISSUE TITLE
Type specs issue with Dialyzer

### ISSUE THREAD

**Issue by SerikDM** [Nordix/eredis_cluster#71]
Code:
```
case :eredis_cluster.qa :db, ["PING"] do
  [ok: "PONG"] -> true
  _ -> false
end
```

Error:
```
The pattern can never match the type.

Pattern:
[{:ok, <<80, 79, 78, 71>>}]

Type:

  [
    {:error, :invalid_cluster_command | :no_connection | :tcp_closed | bitstring()}
    | {:ok, :undefined | [:undefined | bitstring()]}
  ]
  | {:error, :no_connection}
```

Code works correctly, however `"PONG"` doesn't match `:undefined | [:undefined | bitstring()]` typespecs.

Erlang/OTP 25
Elixir (1.14.2)

**Comment by zuiderkwast** [comment]
I don't know Elixir syntax that well. Are `[ok: "PONG"]` and `[{:ok, <<80, 79, 78, 71>>}]` the same pattern? They look very different to me. Can you translate it to Erlang please?

Anyway, the type specs in `eredis_cluster` are a mess. We should be using the types from `eredis` instead of defining our own types, since `eredis_cluster` returns the same things as `eredis`. (And whenever we see `bitstring()` it should actually be `binary()` since we don't accept or return non-multiple-of-8 bits, and other problems.) If you want to clean this mess up, you're welcome to post a PR. :)

The simple solution is probably to fix the return type of `qa`. Looking at it quickly, my guess is that changing `[redis_transaction_result()]` to `[redis_result()]` in the `qa` spec solves your problem.

**Comment by SerikDM** [comment]
> Are [ok: "PONG"] and [{:ok, <<80, 79, 78, 71>>}] the same pattern?

Yes, it's essentially the same thing. Sorry I'm not good with Erlang.

Main issue is, positive response type has `[bitstring()]` while actual returned value is `bitstring()` without list wrapper.

**Comment by zuiderkwast** [comment]
> essentially the same thing

The work "essentially" hints to me that it's not exactly the same thing. :) Is it or is it not?

> positive response type has `[bitstring()]` while actual returned value is `bitstring()`

That confirms what I suggested as the simple fix, right? Have you looked at the types in eredis_cluster.hrl?

**Comment by SerikDM** [comment]
> The word "essentially" hints to me that it's not exactly the same thing. :) Is it or is it not?

Yes it is the same thing.

I checked the files, and your suggestion would fix my issue. However due to lack of familiarity with codebase overall I can't tell what else would be affected by this change.

**Comment by zuiderkwast** [comment]
> I checked the files, and your suggestion would fix my issue. However due to lack of familiarity with codebase overall I can't tell what else would be affected by this change.

Great. Correcting the type will probably not break anything. We have CI job which runs dialyzer but apparently it doesn't run dialyzer on our tests. I found out just now that `rebar3 as test dialyzer` does that and it finds a lot of errors... I haven't checked much but least one of the errors is for `qa`, like your error.
